output_dir: "/tmp/"
run_name: "scooby_run"

data:
  data_path: "/s/project/QNA/scborzoi/submission_data/"
  test_fold: 3
  val_fold: 4
  context_length: 524288
  shift_augs: [-3, 3]
  rc_aug: True

model:
  cell_emb_dim: 14
  num_tracks: 3
  pretrained_model: "johahi/borzoi-replicate-0"

training:
  batch_size: 1
  lr: 1e-4
  wd: 1e-6
  clip_global_norm: 1.0
  warmup_steps: 1000
  num_epochs: 40
  eval_every_n: 256
  total_weight: 0.2